### ISSUE TITLE
Testing coverage for `FraxTest`

### ISSUE THREAD

**Issue by pegahcarter** [FraxFinance/frax-standard-solidity#18]
This is a good first issue for anyone wanting to contribute to Frax Protocol.

Inspired by @tom2o17 in https://github.com/FraxFinance/frax-template/pull/13#pullrequestreview-1863780333, we need full test coverage on [`FraxTest.sol`](https://github.com/FraxFinance/frax-standard-solidity/blob/master/src/FraxTest.sol).

Please comment on this issue if you want to own this task and submit a PR once ready for us to review.  Once approved, we will merge your improvements into main.

The coverage can be completed within [`TestMultipleSetup.t.sol`](https://github.com/FraxFinance/frax-standard-solidity/blob/master/test/TestMultipleSetup.t.sol) or a test file of your choosing.  If you choose to create a new file, please give a description on the motivation and remove the old aforementioned test file.

**Comment by 0xJayPi** [comment]
I can work on this one, please assing it to me
