### ISSUE TITLE
Upgrade to OZ 5.0

### ISSUE THREAD

**Issue by pegahcarter** [FraxFinance/frax-standard-solidity#5]
After four months of OZ 5.0 live we will update our OZ imports from 4.9.3 to 5.0 as the new release should be live long enough to trust there are no hidden bugs.  This puts our upgrade around end of January.

@samkazemian @DrakeEvans @FortisFortuna @denett is this time span reasonable?  5.0 has [significant](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v5.0.0) changes over 4.x, especially over access control, governance, and tokens.

**Comment by FortisFortuna** [comment]
I am personally down to rip off the bandaid now and just do it. Reason being we have several projects coming up (FXB, Frax Oracles, frxETH V2, etc). Fraxchain might be problematic @0xalex88 @DrakeEvans?

**Comment by 0xalex88** [comment]
For Fraxchain that'll mean upgrading the @openzeppelin-new dependency to 5.0 right?

On our contracts we use (from @openzeppelin-new which is 4.9.3)
 - ERC20Permit
 - ERC20
 - ERC20Burnable
 - EIP712
 - IERC20Permit
 - ProxyAdmin
 - TransparentUpgradeableProxy
plus some others from @openzeppelin (the older version that matches optimism ones).

Should we then remove all the references to the old openzeppelin and only use 5.0 for L2 contracts?
I can try to bump the version and run the tests and redeploy the L2.

**Comment by FortisFortuna** [comment]
> For Fraxchain that'll mean upgrading the @openzeppelin-new dependency to 5.0 right?
> 
> On our contracts we use (from @openzeppelin-new which is 4.9.3)
> 
> * ERC20Permit
> * ERC20
> * ERC20Burnable
> * EIP712
> * IERC20Permit
> * ProxyAdmin
> * TransparentUpgradeableProxy
>   plus some others from @OpenZeppelin (the older version that matches optimism ones).
> 
> Should we then remove all the references to the old openzeppelin and only use 5.0 for L2 contracts? I can try to bump the version and run the tests and redeploy the L2.

So if we upgrade, we just need to go into https://github.com/FraxFinance/dev-fraxchain-contracts and make sure it compiles with the new OZ 5.0?

**Comment by 0xalex88** [comment]
> So if we upgrade, we just need to go into https://github.com/FraxFinance/dev-fraxchain-contracts and make sure it compiles with the new OZ 5.0?

Yes (by updating the package.json for @openzeppelin-new and making sure l2 contracts only use that dependency), make sure tests pass and maybe do some manual checks after they're deployed.

**Comment by FortisFortuna** [comment]
I am ok with doing this now, unless there are objections

**Comment by 0xalex88** [comment]
> I am ok with doing this now, unless there are objections

I'll give it a try and redeploy

**Comment by pegahcarter** [comment]
Sounds good.  I'll rip the band-aid off the other repos I'm working on as well and get us to 5.0.

**Comment by FortisFortuna** [comment]
Closed with https://github.com/FraxFinance/frax-standard-solidity/pull/8
